version: 2.1
jobs:
  live:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
            - run:
          name: Build Docker image
          command: |
            docker build -t $APP_IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            docker tag $APP_IMAGE_NAME:latest $APP_IMAGE_NAME:$CIRCLE_SHA1
            docker push $APP_IMAGE_NAME:latest
            docker push $APP_IMAGE_NAME:$CIRCLE_SHA1
workflows:
  version: 2
  build-strongswan-vpn:
    jobs:
      - live:
          context: org-wide
          filters:
            branches:
              only: master
